### ISSUE TITLE
Cannot find module 'url-extractor'

### ISSUE THREAD

**Issue by anomalyst** [gajus/gitdown#40]
Please update README to handhold n00bs thru installing pre-requisites.
I am evidently missing some subtle aspect of installing gitdown/
You can reproduce the issue as follows:
```bash
$ sudo npm install gitdown -g
$ wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.23.2/install.sh | bash
$ nvm install iojs
$ npm install url-extractor
$ gitdown ./foo.gd --output-file ./foo.md
Error: Cannot find module 'url-extractor'
$ cat foo.gd 
{"gitdown": "include", "file": " "./wheeler.sh"}
cat wheeler.sh
#!/bin/sh
#
#       wheeler.sh
#       add wheel group to acl
#
if [ $UID -ne 0 ]; then
    echo "Superuser/root privileges are required to run this script."
    echo "e.g. \"sudo $0\""
    exit 1
fi
chgrp -R wheel $1
chmod -R g+rwx $1
```

**Comment by bbohling** [comment]
Looks like there is an issue with the url-extractor module...the JavaScript isn't present. You can test this yourself:

```shell
npm install url-extractor
```

Or you can simply verify in the **node_modules** directory of gitdown that the url-extractor has no JavaScript files...only package.json, node_modules, and LICENSE.

**Comment by gajus** [comment]
@bbohling It appears to be url-extractor release issue. I have released v2.0.1 (@ed2e9e90f11279f0d3c609050761e2d7b5db14de). Please do:

```sh
rm -fr ./node_modules
npm cache clear
npm install
```

**Comment by bbohling** [comment]
Yes, that is one of the first things I always try...even did it again this morning to be certain and I still get the same error.

```shell
~/Projects/Testing/gitdown
📷  $ ls
debugging.md node_modules package.json
~/Projects/Testing/gitdown
📷  $ rm -fr ./node_modules
~/Projects/Testing/gitdown
📷  $ npm cache clear
~/Projects/Testing/gitdown
📷  $ npm install
npm WARN package.json gitdown@1.0.0 No description
npm WARN package.json gitdown@1.0.0 No repository field.
npm WARN package.json gitdown@1.0.0 No README data
~/Projects/Testing/gitdown
📷  $ git
git                         git-contrib                 git-delete-submodule        git-graft                   git-obliterate              git-repl                    git-touch                   gitexport
git-alias                   git-count                   git-delete-tag              git-ignore                  git-pull-request            git-setup                   git-undo                    github-email
git-archive-file            git-create-branch           git-effort                  git-info                    git-rebase-patch            git-shell                   git-upload-archive          gitk
git-back                    git-credential-osxkeychain  git-extras                  git-line-summary            git-receive-pack            git-show-tree               git-upload-pack             gittower
git-bug                     git-cvsserver               git-feature                 git-local-commits           git-refactor                git-squash                  git_branch
git-changelog               git-delete-branch           git-fresh-branch            git-lock                    git-release                 git-subtree                 git_info
git-commits-since           git-delete-merged-branches  git-gh-pages                git-missing                 git-rename-tag              git-summary                 gitdown
~/Projects/Testing/gitdown
📷  $ gitdown ./debugging.md --output-file ./debugging2.md
module.js:328
    throw err;
    ^

Error: Cannot find module 'url-extractor'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/gitdown.js:13:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/index.js:5:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/bin/index.js:74:19
    at Object.<anonymous> (/Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/bin/index.js:79:3)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by gajus** [comment]
> npm WARN package.json gitdown@1.0.0 No description
> npm WARN package.json gitdown@1.0.0 No repository field.
> npm WARN package.json gitdown@1.0.0 No README data

You are running gitdown v1.0.0. The current version is v2.4.7.

**Comment by bbohling** [comment]
That is from MY package.json. I actually am using 2.4.7

```shell
~/Projects/Testing/gitdown
📷  $ npm -g ls --depth=0
/Users/bbohling/.nvm/versions/node/v4.2.6/lib
├──
├── check-dependencies@0.12.0
├── doctoc@1.0.0
├── gitdown@2.4.7
└── npm@2.14.12

~/Projects/Testing/gitdown
📷  $ gitdown ./debugging.md --output-file ./debugging2.md
module.js:328
    throw err;
    ^

Error: Cannot find module 'url-extractor'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/gitdown.js:13:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/index.js:5:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/bin/index.js:74:19
    at Object.<anonymous> (/Users/bbohling/.nvm/versions/node/v4.2.6/lib/node_modules/gitdown/dist/bin/index.js:79:3)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by bbohling** [comment]
Test this yourself:

```shell
npm install url-extractor
```

Then look in the **node_modules/url-extractor** directory...there is no JavaScript file.

**Comment by gajus** [comment]
@bbohling 

```
$ npm install
$ tree ./node_modules/url-extractor
./node_modules/url-extractor
├── LICENSE
├── README.md
├── dist
│   ├── constants.js
│   ├── constants.js.map
│   ├── extractUrls.js
│   ├── extractUrls.js.map
│   ├── extractUrlsFromMarkdown.js
│   ├── extractUrlsFromMarkdown.js.map
│   ├── index.js
│   └── index.js.map
└── package.json

1 directory, 11 files
```

**Comment by claylo** [comment]
For what it's worth, I'm having this same issue today. gitdown 2.4.7, url-extractor 2.0.1. Seems to be a problem with url-extrator's package.json, which states as of [2.0.0](https://github.com/gajus/url-extractor/commit/e188bce91996dab72756c628b0856217ce754788#diff-b9cfc7f2cdf78a7f4b91a753d10865a2):

```json
{
  "main": "./dist/urlExtractor.js"
}
```
... which is a file that does not exist in the tree @gajus posted a few days ago.

**Comment by gajus** [comment]
@claylo good catch.

I have patched https://github.com/gajus/url-extractor/commit/3074ceebf63146f396d30cd1dd958e1389205f00.

For this to work, someone needs to submit a PR for Gitdown to use the [new `url-extractor` methods](https://github.com/gajus/url-extractor#extract-urls-from-markdown). The affected code is:

* https://github.com/gajus/gitdown/blob/a254b825a3a0293b11cd11267b2f74aa672ebe7b/src/gitdown.js#L112

**Comment by gajus** [comment]
Thank you. v2.4.8 have been released.
